export const manifestsCatalog = [
  { manifestId: 'https://files.tetras-libre.fr/dev/multicanva-video.json' },
  { manifestId: 'https://files.tetras-libre.fr/dev/test-vertical-video.json' },
  { manifestId: 'https://files.tetras-libre.fr/dev/Heterogeneous-media-on-several-canvases.json' },
  { manifestId: 'https://files.tetras-libre.fr/dev/Clock/manifestWithAnnotationTemplates_MAE.json' },
  { manifestId: 'https://files.tetras-libre.fr/dev/Clock/manifest.json' },
  { manifestId: 'https://files.tetras-libre.fr/dev/Hakanai/manifest/manifest.json' },
  { manifestId: 'https://dzkimgs.l.u-tokyo.ac.jp/videos/iiif_in_japan_2017/manifest.json' },
  { manifestId: 'https://iiif.io/api/cookbook/recipe/0219-using-caption-file/manifest.json' },
  { manifestId: 'https://preview.iiif.io/cookbook/master/recipe/0003-mvm-video/manifest.json' },
  { manifestId: 'https://iiif.io/api/cookbook/recipe/0065-opera-multiple-canvases/manifest.json' },
  { manifestId: 'https://iiif.io/api/cookbook/recipe/0064-opera-one-canvas/manifest.json' },
  { manifestId: 'https://iiif.io/api/cookbook/recipe/0074-multiple-language-captions/manifest.json' },
  { manifestId: 'https://iiif.harvardartmuseums.org/manifests/object/299843' },
  { manifestId: 'https://iiif.io/api/cookbook/recipe/0002-mvm-audio/manifest.json' },
];
